### ISSUE TITLE
Error: (%d)

### ISSUE THREAD

**Issue by TAKASHITOKYO** [GamehunterKaan/AutoPWN-Suite#11]
hi how to fix error code in kali linux ===> (Error: (%d) format: a real number is required, not str)
go to path /home/name/name/Autopwn/modules/scanner.py
& change this %d to %s
thanks GamehunterKaan for AutoPwn-Suite

**Comment by GamehunterKaan** [comment]
Can you please provide a screenshot and additional information about the issue so I can try to understand where it fails?

**Comment by GamehunterKaan** [comment]
OK, I was able to reproduce the bug by a chance, should be fixed now.
