### ISSUE TITLE
NameError: name 'sleep' is not defined

### ISSUE THREAD

**Issue by faisalfs10x** [GamehunterKaan/AutoPWN-Suite#2]
![image](https://user-images.githubusercontent.com/51811615/171568150-864287dc-cab2-49e9-88e2-d7936ae47329.png)

fix: `from time import sleep`
![image](https://user-images.githubusercontent.com/51811615/171568204-9b48b354-5753-4c25-afe9-e17aa0595cd8.png)

**Comment by GamehunterKaan** [comment]
Fixed the issue, thanks a lot for reporting. Auto-PWN Suite has been getting a loot of traffic today. So may I ask you about how did you find this project?
