### ISSUE TITLE
Can't scan with nmap

### ISSUE THREAD

**Issue by innerfirebg** [GamehunterKaan/AutoPWN-Suite#21]
**Describe the bug**
Can't scan ports from discovered hosts.

**To Reproduce**
start the program using last version from repository or from deb file (v1.5.1)
Chose one IP that is alive and have open ports
then wait and i see this:
![image](https://user-images.githubusercontent.com/47434937/175052434-d0ce184b-d926-4130-8472-94201d19798f.png)

**Expected behavior**
To see open ports

**Desktop (please complete the following information):**
 - OS: Parrot OS

**Comment by innerfirebg** [comment]
Not even port, just try to scan some IP in private network using OpenVPN, when I try to scan it manually, it's works using nmap with default settings.

**Comment by innerfirebg** [comment]
![image](https://user-images.githubusercontent.com/47434937/175293114-2f3d2137-d673-4e65-8663-b32775ef2337.png)

**Comment by GamehunterKaan** [comment]
Try specifying you vpn interface as nmap flags to use with the `-nf` argument.

`sudo autopwn-suite -y -nf="-e tun0"`

**Comment by innerfirebg** [comment]
It's the same…

> Try specifying you vpn interface as nmap flags to use with the `-nf` argument.
> 
> `sudo autopwn-suite -y -nf="-e tun0"`

It's the same…

**Comment by innerfirebg** [comment]
Maybe it's because of using VPN, but I don't know why for now.

**Comment by GamehunterKaan** [comment]
I am pretty sure its VPN related.
