### ISSUE TITLE
no howto using google cloud shell

### ISSUE THREAD

**Issue by nicolascharbonnier** [GamehunterKaan/AutoPWN-Suite#36]
hi, 
i try it using google cloud shell, but you don't give the process, so i check if there is any autopwn-suite "exe" file, but no
```
_user@cloudshell:~/cloudshell_open/AutoPWN-Suite$ pwd
/home/user/cloudshell_open/AutoPWN-Suite
nocktames@cloudshell:~/cloudshell_open/AutoPWN-Suite$ find . -iname autopwn
user@cloudshell:~/cloudshell_open/AutoPWN-Suite$_
```

so there is any process ?

**Comment by nicolascharbonnier** [comment]
it's ok using copy from git & auto-install then
but onto google cloud shell replace pib using pib3 and it works fine !

**Comment by GamehunterKaan** [comment]
Cloud shell automatically clones the repo. In order to run the script you have to do `python autopwn.py`
