### ISSUE TITLE
TypeError: 'type' object is not subscriptable on MacOS

### ISSUE THREAD

**Issue by Fipsa** [GamehunterKaan/AutoPWN-Suite#37]
**Describe the bug**
In MacOs (Monterey) Terminal I get this error:

Traceback (most recent call last):
  File "autopwn.py", line 5, in <module>
    from modules.banners import print_banner
  File "/Users/xxx/AutoPWN-Suite/modules/banners.py", line 5, in <module>
    from modules.utils import get_terminal_width
  File "/Users/xxx/AutoPWN-Suite/modules/utils.py", line 499, in <module>
    def UserConfirmation() -> tuple[bool, bool, bool]:
TypeError: 'type' object is not subscriptable

**To Reproduce**
sudo python3 autopwn.py -y

**Desktop (please complete the following information):**
 - OS: Monterey
 - Version 12.5

**Comment by GamehunterKaan** [comment]
What version of python are you using?

**Comment by dawstudiocenter** [comment]
Same error on my mac / Monterey 12.5 .
Python version is 3.8.9.

**Comment by GamehunterKaan** [comment]
> Python version is 3.8.9.

This project was created for python 3.10. I recommend you to try using that version.

**Comment by Fipsa** [comment]
Thank you. Now I'm on python 3.10.
New problem:
Traceback (most recent call last):
  File "/Users/xxx/AutoPWN-Suite/autopwn.py", line 9, in <module>
    from modules.scanner import AnalyseScanResults, DiscoverHosts, NoiseScan, PortScan
  File "/Users/xxx/AutoPWN-Suite/modules/scanner.py", line 6, in <module>
    from nmap import PortScanner
ImportError: cannot import name 'PortScanner' from 'nmap' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nmap/__init__.py)

**Comment by GamehunterKaan** [comment]
Did you install dependencies using `sudo pip install -r requirements.txt` ?

**Comment by Fipsa** [comment]
Yes. Still the same error:

Traceback (most recent call last):
  File "/Users/xxx/AutoPWN-Suite/autopwn.py", line 9, in <module>
    from modules.scanner import AnalyseScanResults, DiscoverHosts, NoiseScan, PortScan
  File "/Users/xxx/AutoPWN-Suite/modules/scanner.py", line 6, in <module>
    from nmap import PortScanner
ImportError: cannot import name 'PortScanner' from 'nmap' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nmap/__init__.py)

**Comment by GamehunterKaan** [comment]
That is weird. After every commit automatic tests are being ran on Linux and MacOS. [Just like this one.](https://github.com/GamehunterKaan/AutoPWN-Suite/runs/7819016657?check_suite_focus=true) I have also had other people contacted me after using it on MacOS telling that its working fine. Maybe there is an issue with python site-packages? Running `pip uninstall nmap` and `pip install python-nmap` might fix it. Or you might have to manualy delete nmap package from site-packages directory.

**Comment by Fipsa** [comment]
After adding Home-brew (as in your exemple on MacOs) it's worse (no more location :

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/autopwn-suite", line 5, in <module>
    from autopwn_suite.autopwn import main
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/autopwn_suite/autopwn.py", line 9, in <module>
    from modules.scanner import AnalyseScanResults, DiscoverHosts, NoiseScan, PortScan
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/autopwn_suite/modules/scanner.py", line 6, in <module>
    from nmap import PortScanner
ImportError: cannot import name 'PortScanner' from 'nmap' (unknown location)

**Comment by GamehunterKaan** [comment]
Did you run `pip install -r requirements.txt` after?

**Comment by dawstudiocenter** [comment]
I finally get it running on fresh MacOs Monterey 2.5 upgrade.
I need to : 
- install later python 3.10.6 (from there : https://www.python.org/ftp/python/3.10.6/python-3.10.6-macos11.pkg ) and then latest pip3 2.2.2.2 version.
- install 'nmap' and 'ip' command tool (thanks to homebrew, nota: to install ip tool = brew install iproute2mac )
Hope it helps.

**Comment by Fipsa** [comment]
I did it. Python 3.10.6, pip3 22.2.2 and iproute2mac.
After few errors I relinked files:

- brew link --overwrite python@3.10
- brew unlink python@3.10 && brew link python@3.10

The: "sudo python3 autopwn.py -y" same error:

Traceback (most recent call last):
  File "/Users/xxx/AutoPWN-Suite/autopwn.py", line 9, in <module>
    from modules.scanner import AnalyseScanResults, DiscoverHosts, NoiseScan, PortScan
  File "/Users/xxx/AutoPWN-Suite/modules/scanner.py", line 6, in <module>
    from nmap import PortScanner
ImportError: cannot import name 'PortScanner' from 'nmap' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nmap/__init__.py)

I deleted and reinstalled nmap, same error.

Here is the content of "__init__.py":

from .nmap import nmap


And content of "nmap.py" file:

def nmap(a, b, c, d, curvefn=None, normfn=None):
    """
    Returns a function that maps a number n from range (a, b) onto a range
    (x, y). If no curvefn is given, linear mapping will be used. Optionally a
    normalisation function normfn can be provided to transform output.
    """
    if not curvefn:
        curvefn = lambda x: x

    def map(n):
        r = 1.0 * (n - a) / (b - a)
        out = curvefn(r) * (d - c) + c
        if not normfn:
            return out
        return normfn(out)
    return map


if __name__ == '__main__':
    mapfn = nmap(0, 100, 500, 1000)
    assert mapfn(0) == 500
    assert mapfn(100) == 1000
    assert mapfn(50) == 750
    print('done')

So, where is 'PortScanner' in 'nmap'?

**Comment by GamehunterKaan** [comment]
You installed the ["nmap"](https://pypi.org/project/nmap/) package. You have to install ["python-nmap"](https://pypi.org/project/python-nmap/) package instead.

**Comment by Fipsa** [comment]
Installation front folder by "install" not changed the problem, so I replaced folder nmap directly in "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/"
It's work !!!
Thank you very much!

**Comment by GamehunterKaan** [comment]
Your welcome! I am glad I could help. Closing this issue as completed.
