### ISSUE TITLE
v2.1.2 on git repository

### ISSUE THREAD

**Issue by grandaor** [GamehunterKaan/AutoPWN-Suite#38]
**Describe the bug**
I clone this project git on my machine and I've this message when i use autopwn-suite :
```
[13:06:45] WARNING  [*] Your version of AutoPWN Suite is outdated. Update   logger.py:59
                    is advised. 
```
I checked the version and i've this :
```
agrestic@blade15 | ~ | git | AutoPWN-Suite | main 
$ sudo python3 autopwn.py --version
AutoPWN Suite v2.1.1
```
I switched to the commit with tags on le the latest version v2.1.2 and I've this :
```
agrestic@blade15 | ~ | git | AutoPWN-Suite | ⚓v2.1.2
$ sudo python3 autopwn.py --version
AutoPWN Suite v2.1.1
```

Thanks in advance for your replies
I very like this tool

**Comment by GamehunterKaan** [comment]
Seems like I forgot to bump the version. Thanks for reporting!
