### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by VoXaN24** [GamehunterKaan/AutoPWN-Suite#39]
**Describe the bug**
"TypeError: 'type' object is not subscriptable" in utils.py

**To Reproduce**
1. Execute the .py

**Screenshots**
![image](https://user-images.githubusercontent.com/30030208/187172201-6f2d7ce8-0a76-4cd3-9e31-d4b0040c4891.png)

**Desktop (please complete the following information):**
 - OS: Debian
 - Version : 10
 - Python 3
 
![raw](https://user-images.githubusercontent.com/30030208/187172618-07be508b-549b-4c13-b69b-89467712380f.png)

**Comment by GamehunterKaan** [comment]
Debian comes pre-installed with python3.9 by default. Please install python3.10 and try again.

**Comment by VoXaN24** [comment]
It work thank's !
