### ISSUE TITLE
zstd compression of .deb is not supported on Kali

### ISSUE THREAD

**Issue by ksb4ever** [GamehunterKaan/AutoPWN-Suite#4]
Not possible to install package on Kali Linux (also on Debian), because of zstd compression format.

**To Reproduce**
1. Download the package
2. Install it by dpkg -i
3. get "dpkg-deb: error: archive 'autopwn-suite_1.0.4.deb' uses unknown compression for member 'control.tar.zst', giving up"

**Expected behavior**
Package fully installed

**Desktop (please complete the following information):**
OS:
1) Kali Linux 2022.2 (Rolling)
2) Debian Bullseye

**Additional context**
autopwn-suite_1.0.4.deb: Debian binary package (format 2.0), with control.tar.zs, data compression zst
Perhaps zstd is supported on Ubuntu derrivatives

**Comment by GamehunterKaan** [comment]
Built it again using debian, and installed it using apt-get and dpkg. Seems to be working fine in both Debian and Kali. Here's the new package, please let me now if you face any problems.

[fix.zip](https://github.com/GamehunterKaan/AutoPWN-Suite/files/8834598/fix.zip)

![Screenshot_20220603_205201](https://user-images.githubusercontent.com/68380968/171919525-c9858b13-2b38-4706-a11e-2ae59122f259.png)
![Screenshot_20220603_204654](https://user-images.githubusercontent.com/68380968/171919530-45db68f0-d96c-48ea-85ba-9ca8b30bf209.png)

**Comment by ksb4ever** [comment]
Now it is fine, perhaps this issue can be closed now.
