### ISSUE TITLE
Self SIgned Cert

### ISSUE THREAD

**Issue by rikosintie** [GamehunterKaan/AutoPWN-Suite#41]
Hello,
New to AutoPwn, Ubuntu 22.04.1. Running in a venv environment. When it starts the web application scanning it crashes with a self-signed cert error. In the use case I have all devices use the manufacturer's self-signed cert. I looked for a switch to disable the cert check but I didn't see one. 

I can supply any information needed to help troubleshoot. 

Thanks! 
Michael

[self-signed.txt](https://github.com/GamehunterKaan/AutoPWN-Suite/files/9486175/self-signed.txt)

**Comment by GamehunterKaan** [comment]
I'll look into it. Thanks for reporting the issue!
