### ISSUE TITLE
Banner errors

### ISSUE THREAD

**Issue by shadowdevnotreal** [GamehunterKaan/AutoPWN-Suite#43]
Hey, love this app and it worked in Ubuntu until recently and I'm getting banner errors now.

I'll clip and paste the error as soon as my encryption is done, but I didn't update the repo, just got an OS update and it stopped working.

**Comment by GamehunterKaan** [comment]
Please follow the [bug report issue template.](https://github.com/GamehunterKaan/AutoPWN-Suite/issues/new?assignees=&labels=&template=bug_report.md&title=) The information you gave is not enough.
