### ISSUE TITLE
Error  cannot access local variable 'data' where it is not associated with a value    

### ISSUE THREAD

**Issue by ZarTek-Creole** [GamehunterKaan/AutoPWN-Suite#46]
[ ===] Searching vulnerability database for Postfix smtpd ...[08:32:08] ERROR    [-] cannot access local variable 'data' where it is not associated with a value                                                                                                                              logger.py:57
[=   ] Searching vulnerability database for NLnet Labs NSD ...[08:32:16] ERROR    [-] cannot access local variable 'data' where it is not associated with a value                                                                                                                              logger.py:57

**Comment by bugtraqv1** [comment]
same

**Comment by rajivraj** [comment]
same

**Comment by GamehunterKaan** [comment]
Fixed with #48
