### ISSUE TITLE
ERROR  [-] cannot access local variable 'data' where it is not associated with a value

### ISSUE THREAD

**Issue by sithortodox** [GamehunterKaan/AutoPWN-Suite#47]
[21:28:59] INFO     [+] Searching vulnerability database for 2 keyword(s) ...                                                                                             logger.py:55
[=== ] Searching vulnerability database for OpenSSH 8.2p1 Ubuntu 4ubuntu0.9 ...[21:29:03] ERROR    [-] cannot access local variable 'data' where it is not associated with a value                                                                       logger.py:57
[==  ] Searching vulnerability database for nginx 1.18.0 ...[21:29:07] ERROR    [-] cannot access local variable 'data' where it is not associated with a value                                                                       logger.py:57

**Comment by GamehunterKaan** [comment]
Fixed with #48

**Comment by CyberAdmin1708** [comment]
Please what i must change it or is the module updated? I have the same Issue and the newest version. @GamehunterKaan  can you help me?

**Comment by OpM3TA** [comment]
> Please what i must change it or is the module updated? I have the same Issue and the newest version. [@GamehunterKaan](https://github.com/GamehunterKaan) can you help me?

currently exp this myself using pip/python 3.12 it seems.
